### ISSUE TITLE
Red lights stay

### ISSUE THREAD

**Issue by Goten87** [troelsbjerre/Bottleneck#10] opened 2016-10-02 16:18 UTC
i keep the red light on all my things even when i just place them
Version (0.4.0)
going back to 0.3.3 now to see what that will do

Edit: 0.3.3 fixed it right away

**Comment by troelsbjerre** [comment] 2016-10-02 17:17
Thank you for the heads up. Could I get you to try something for me, to help me track down the problem: disable 0.4.0, save, enable 0.4.0, load, and tell me whether the problem is still there?

**Comment by Goten87** [comment] 2016-10-02 17:47
ok i downloaded 0.4 again disabled the mod loaded the game saved again stopped toggled it on went back removed a miner placed it down and its red light again

**Comment by troelsbjerre** [comment] 2016-10-02 21:21
Yeah, that looks weird. Could I get you to send me the savegame?

**Comment by Goten87** [comment] 2016-10-03 13:59
[Debug Bottleneck.zip](https://github.com/troelsbjerre/Bottleneck/files/506379/Debug.Bottleneck.zip)
so i tested it with all my mods off exept base and bottleneck and its still doing it
to make it work pick up a miner with green light put it back and it will become a red light and staying red
hope the save helps u

**Comment by troelsbjerre** [comment] 2016-10-03 17:03
Thank you! It turns out to be an optimization that goes rogue. I have no excuse for why I didn't catch this bug before releasing 0.4.0. The bug would show up on any mining drill placed after installing 0.4.0. This is fixed by 0.4.3

**Comment by Goten87** [comment] 2016-10-03 17:19
lets update then xD

**Comment by troelsbjerre** [comment] 2016-10-03 18:30
Great :)  Thanks for helping out!

**Closed by troelsbjerre** 2016-10-03 18:30 UTC
