### ISSUE TITLE
The colors (but particularly the yellow) are very hard to see

### ISSUE THREAD

**Issue by mybuddymichael** [troelsbjerre/Bottleneck#69] opened 2020-02-02 16:06 UTC
Thanks for your hard work on this mod! It is wonderfully helpful.

However, I'm currently finding the yellow very hard to notice. It is quite muted and just blends in with everything else. I'd predict that the mod would benefit in utility and usability if all the colors had a little more "pop".

Thanks again and take care!

**Comment by troelsbjerre** [comment] 2020-02-02 16:20
This is a duplicate of #66.

**Closed by troelsbjerre** 2020-02-02 16:20 UTC
